// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
declare namespace Cloudflare {
	interface Env {
		API_URL?: string;
	}
}
interface Env extends Cloudflare.Env {}
