# fly.toml app configuration file generated for bulktrack-api on 2025-04-19T12:04:57+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bulktrack-api'
primary_region = 'nrt'

[build]
  dockerfile = 'apps/api/Dockerfile'

[http_service]
  internal_port = 5555
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
