// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: menu_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (
  menu_id, exercise, set_order, planned_reps
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, menu_id, exercise, set_order, planned_reps
`

type CreateMenuItemParams struct {
	MenuID      pgtype.UUID `json:"menu_id"`
	Exercise    string      `json:"exercise"`
	SetOrder    int32       `json:"set_order"`
	PlannedReps pgtype.Int4 `json:"planned_reps"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.MenuID,
		arg.Exercise,
		arg.SetOrder,
		arg.PlannedReps,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.Exercise,
		&i.SetOrder,
		&i.PlannedReps,
	)
	return i, err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items
WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, id)
	return err
}

const getMenuItem = `-- name: GetMenuItem :one
SELECT id, menu_id, exercise, set_order, planned_reps FROM menu_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMenuItem(ctx context.Context, id uuid.UUID) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItem, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.Exercise,
		&i.SetOrder,
		&i.PlannedReps,
	)
	return i, err
}

const listMenuItemsByMenu = `-- name: ListMenuItemsByMenu :many
SELECT id, menu_id, exercise, set_order, planned_reps FROM menu_items
WHERE menu_id = $1
ORDER BY set_order
`

func (q *Queries) ListMenuItemsByMenu(ctx context.Context, menuID pgtype.UUID) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByMenu, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.Exercise,
			&i.SetOrder,
			&i.PlannedReps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET exercise = $2, planned_reps = $3
WHERE id = $1
RETURNING id, menu_id, exercise, set_order, planned_reps
`

type UpdateMenuItemParams struct {
	ID          uuid.UUID   `json:"id"`
	Exercise    string      `json:"exercise"`
	PlannedReps pgtype.Int4 `json:"planned_reps"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem, arg.ID, arg.Exercise, arg.PlannedReps)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.Exercise,
		&i.SetOrder,
		&i.PlannedReps,
	)
	return i, err
}
