// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID                      uuid.UUID          `json:"id"`
	Name                    string             `json:"name"`
	MainTargetMuscleGroupID pgtype.UUID        `json:"main_target_muscle_group_id"`
	IsCustom                pgtype.Bool        `json:"is_custom"`
	CreatedByUserID         pgtype.Text        `json:"created_by_user_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type ExerciseTargetMuscleGroup struct {
	ExerciseID    uuid.UUID `json:"exercise_id"`
	MuscleGroupID uuid.UUID `json:"muscle_group_id"`
}

type Menu struct {
	ID          uuid.UUID          `json:"id"`
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MenuItem struct {
	ID                     uuid.UUID   `json:"id"`
	MenuID                 pgtype.UUID `json:"menu_id"`
	ExerciseID             pgtype.UUID `json:"exercise_id"`
	SetOrder               int32       `json:"set_order"`
	PlannedSets            pgtype.Int4 `json:"planned_sets"`
	PlannedReps            pgtype.Int4 `json:"planned_reps"`
	PlannedIntervalSeconds pgtype.Int4 `json:"planned_interval_seconds"`
}

type MuscleGroup struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Set struct {
	ID         uuid.UUID      `json:"id"`
	WorkoutID  pgtype.UUID    `json:"workout_id"`
	ExerciseID pgtype.UUID    `json:"exercise_id"`
	SetOrder   int32          `json:"set_order"`
	WeightKg   pgtype.Numeric `json:"weight_kg"`
	Reps       int32          `json:"reps"`
	Rir        pgtype.Numeric `json:"rir"`
	Rpe        pgtype.Numeric `json:"rpe"`
}

type WeeklyVolume struct {
	ID            uuid.UUID      `json:"id"`
	UserID        string         `json:"user_id"`
	WeekStartDate pgtype.Date    `json:"week_start_date"`
	TotalVolume   pgtype.Numeric `json:"total_volume"`
	EstOneRm      pgtype.Numeric `json:"est_one_rm"`
	ExerciseCount int32          `json:"exercise_count"`
	SetCount      int32          `json:"set_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Workout struct {
	ID        uuid.UUID          `json:"id"`
	UserID    string             `json:"user_id"`
	MenuID    pgtype.UUID        `json:"menu_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Note      pgtype.Text        `json:"note"`
}
