// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Menu struct {
	ID        uuid.UUID          `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MenuItem struct {
	ID          uuid.UUID   `json:"id"`
	MenuID      pgtype.UUID `json:"menu_id"`
	Exercise    string      `json:"exercise"`
	SetOrder    int32       `json:"set_order"`
	PlannedReps pgtype.Int4 `json:"planned_reps"`
}

type Set struct {
	ID        uuid.UUID      `json:"id"`
	WorkoutID pgtype.UUID    `json:"workout_id"`
	Exercise  string         `json:"exercise"`
	SetOrder  int32          `json:"set_order"`
	WeightKg  pgtype.Numeric `json:"weight_kg"`
	Reps      int32          `json:"reps"`
	Rpe       pgtype.Numeric `json:"rpe"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Nickname  pgtype.Text        `json:"nickname"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WeeklySummary struct {
	UserID      pgtype.UUID `json:"user_id"`
	Week        pgtype.Date `json:"week"`
	TotalVolume int64       `json:"total_volume"`
	Est1rm      interface{} `json:"est_1rm"`
}

type Workout struct {
	ID        uuid.UUID          `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	MenuID    pgtype.UUID        `json:"menu_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Note      pgtype.Text        `json:"note"`
}
