// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error)
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateSet(ctx context.Context, arg CreateSetParams) (Set, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	DeleteMenu(ctx context.Context, id uuid.UUID) error
	DeleteMenuItem(ctx context.Context, id uuid.UUID) error
	DeleteMenuItems(ctx context.Context, menuID pgtype.UUID) error
	DeleteSet(ctx context.Context, id uuid.UUID) error
	DeleteWorkout(ctx context.Context, id uuid.UUID) error
	GetExercise(ctx context.Context, id uuid.UUID) (Exercise, error)
	GetLatestWorkoutIDByMenu(ctx context.Context, arg GetLatestWorkoutIDByMenuParams) (uuid.UUID, error)
	GetMenu(ctx context.Context, id uuid.UUID) (Menu, error)
	GetMenuItem(ctx context.Context, id uuid.UUID) (MenuItem, error)
	GetSet(ctx context.Context, id uuid.UUID) (Set, error)
	GetWorkout(ctx context.Context, id uuid.UUID) (Workout, error)
	ListExercises(ctx context.Context) ([]ListExercisesRow, error)
	ListMenuItemsByMenu(ctx context.Context, menuID pgtype.UUID) ([]ListMenuItemsByMenuRow, error)
	ListMenusByUser(ctx context.Context, userID string) ([]Menu, error)
	ListSetsByWorkout(ctx context.Context, workoutID pgtype.UUID) ([]ListSetsByWorkoutRow, error)
	ListSetsByWorkoutAndExercises(ctx context.Context, arg ListSetsByWorkoutAndExercisesParams) ([]ListSetsByWorkoutAndExercisesRow, error)
	ListWorkoutsByUser(ctx context.Context, userID string) ([]Workout, error)
	UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateSet(ctx context.Context, arg UpdateSetParams) (Set, error)
	UpdateWorkoutNote(ctx context.Context, arg UpdateWorkoutNoteParams) (Workout, error)
}

var _ Querier = (*Queries)(nil)
